{-
   OpenAI API

   APIs for sampling from and fine-tuning language models

   OpenAPI Version: 3.0.0
   OpenAI API API version: 2.0.0
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : OpenAI.API
-}

module OpenAI.API
  ( module OpenAI.API.OpenAI
  ) where

import OpenAI.API.OpenAI